### ISSUE TITLE
PATMOS-x

### ISSUE THREAD

**Issue by simonpf** [SEE-GEO/ccic_climate_record_analysis#2]
- [x] Identify which data is need
- [x] Write download script
- [ ] Pre-process data

**Comment by adriaat** [comment]
I identified which data is likely needed from PATMOS-x: cloud water path, cloud phase, timestamp for each pixel, cloud probability, and cloud fraction. I omit other variables for now.

- They provide a variable called `cloud_mask` (with values `clear`, `probably clear`, `probably cloudy`, `cloudy`) which is redundant with `cloud_probability`: `P(cloud probability > 0.5) = (probably) cloudy`, based on an inspection of the data.
- The cloud water path is computed using the DCOMP algorithm (daytime only, uses an absorption solar channel). There is one cloud phase (`clear`, `water`, `supercooled_water`, `mixed`, `ice`, `unknown`) and cloud water path value per pixel.

PATMOS-x v6.0 is in *final* version up to 2019. From 2020 the files are *preliminary*. All PATMOS-x v6.0 final data has been downloaded and stored only containing the relevant variables (files `*_v1.nc`). The attributes of the variables in the netCDF give details on the values and units.

PS: It takes about one day to download and extract the data from the S3 buckets containing the PATMOS-x CDR using the cluster, with one job per year with 12 processes and 10 running jobs.
