### ISSUE TITLE
ERA5 data

### ISSUE THREAD

**Issue by simonpf** [SEE-GEO/ccic_climate_record_analysis#5]
- [x] Identify required data
- [x] Write download scripts for monthly data download and month by hour 
- [x] Get the data
- [x] Literature background: how is it usually validated? Compared to what datasets?

**Comment by JuliaKukulies** [comment]
> * [ ]  Identify required data
> * [ ]  Write download scripts
> * [ ]  Literature background: how is it usually validated? Compared to what datasets? 
> * [ ]  Pre-process data

**Comment by JuliaKukulies** [comment]
First steps for ERA5 are done. 
Downloaded monthly and monthly by hour: total_column_snow_water + total_column_ice_water, total_cloud_cover

**Comment by erikssonpatrick** [comment]
Please note that total_column_snow_water (SIWP) and total_column_ice_water (CIWP) do not represent all the ice hydrometors. The convective part is missing. If you look at the accumulations, there are Large-scale snowfall and Convective snowfall. SIWP matches the former, while the latter part is missing as column value as convective snow is a diagnostic variable in the form of fluxes. That is, we can not get ERA5's TIWP, just a lower bound for it.
