### ISSUE TITLE
MODIS

### ISSUE THREAD

**Issue by simonpf** [SEE-GEO/ccic_climate_record_analysis#6]
- [x] Identify the variables that can be compared to CCIC 2d_cloud_probability and tiwp.
- [x] Write download script
- [x] Brief literature survey regarding important results
- [x] Draft section in manuscript

**Comment by elliemay481** [comment]
Simon - have you done much work on this section already? I've been working with L3 IWP (and other variable) MODIS data for another project, so I already have some scripts set up for global & zonal means that could be used again here.

**Comment by simonpf** [comment]
That's awesome! I haven't started this. @elliemay481 , would you be able to push the scripts to the repository and I take it from there? I saw you assigned yourself to ISCCP. Would it make more sense for you to take MODIS and I take ISCCP?

**Comment by elliemay481** [comment]
Sure! I haven't started on ISCCP yet either so I'm happy to take MODIS instead, it probably makes more sense.
