### ISSUE TITLE
Breakpoint analysis 

### ISSUE THREAD

**Issue by JuliaKukulies** [SEE-GEO/ccic_climate_record_analysis#7]
- [ ] Identify which method to use for change-point detection (non-parametric or regression-based) and how to implement this (Use python package ruptures? One of the possible methods: Multivariate E.divise )

- [ ] Assess the stability of cloud mask amount based on WMO standards (compare trend in bias to other datasets such as PATMOS, ISCCP, MODIS)

**Comment by simonpf** [comment]
Closing this as it we decided to not pursue this.
